version: "3.8"

x-msk_cluster:
#  existing-cluster:
#    Lookup:
#      Tags:
#        - Name: api-testing

  new-cluster:
    Properties:
      ClusterName: testingcluster
      KafkaVersion: "3.3.1"
      NumberOfBrokerNodes: 2
      BrokerNodeGroupInfo:
        InstanceType: "kafka.m5.large"
        ClientSubnets:
          - x-vpc::vpc::StorageSubnets
      ClientAuthentication:
        Unauthenticated:
          Enabled: False
        Sasl:
          Iam:
            Enabled: true
          Scram:
            Enabled: false
        Tls:
          Enabled: false
      EncryptionInfo:
        EncryptionInTransit:
          InCluster: true
          ClientBroker: TLS
        EncryptionAtRest:
          DataVolumeKMSKeyId: arn:aws:kms:eu-west-1:373709687836:key/4dbcf779-aebc-4c44-8713-3c56b337e4f5 #x-kms::msk-encryption-key::Arn
    MacroParameters:
      StorageScaling:
        MaxInGB: 2048
        Target: 42.0
    Services:
      etl:
        Access:
          MSKCluster: RO
        KafkaAccess:
          Iam:
            topic:
              Admin:
                - my-app-topics*
              Consumer:
                - '*'
            group:
              Producer:
                - my-consumer-group-app
            transactional-id:
              Producer:
                - "*"

x-kms:
  msk-encryption-key:
    Properties: { }
    MacroParameters:
      Alias: alias/msk/testing-encryption-key

services:
  proxy:
    x-scaling:
      Range: 1-4

  backend:
    x-scaling:
      Range: 1-4

  etl:
    x-scaling:
      Range: 0-12
